<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="*" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="*" />
    <PackageReference Include="MediatR" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SentinelQA.Application\SentinelQA.Application.csproj" />
  </ItemGroup>

</Project>
