<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="*" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="*" />
    <PackageReference Include="MongoDB.Driver" Version="*" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="*" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.Design" Version="1.1.0" />
    <PackageReference Include="RabbitMQ.Client" Version="*" />
    <PackageReference Include="StackExchange.Redis" Version="*" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SentinelQA.Application\SentinelQA.Application.csproj" />
    <ProjectReference Include="..\SentinelQA.Domain\SentinelQA.Domain.csproj" />
    <ProjectReference Include="..\SentinelQA.Contracts\SentinelQA.Contracts.csproj" />
  </ItemGroup>

</Project>
