<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="*" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.UnitOfWork" Version="3.1.0" />
    <PackageReference Include="UnitOfWork" Version="0.24.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SentinelQA.Domain\SentinelQA.Domain.csproj" />
    <ProjectReference Include="..\..\SentinelQA.Infrastructure\SentinelQA.Infrastructure.csproj" />
  </ItemGroup>

</Project>
